-- Complète la gamme de brasseries françaises déjà présentes dans le
-- catalogue mais réduites à une seule bière (ex: Brasserie du Mont
-- Blanc), à la demande de l'utilisateur. Aucune nouvelle brasserie :
-- toutes existent déjà dans brewery_locations.

-- 27 nouvelles bières pour 12 brasseries déjà cataloguées.
insert into beers (id, name, brewery, country, style_id, abv, description) values ('mont-blanc-blanche', 'Mont Blanc Blanche', 'Brasserie du Mont Blanc', 'France', 'witbier', 4.7, 'Blanche légère aux notes de blé et d''agrumes, élue meilleure bière du monde en 2013 et 2015.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('mont-blanc-triple-epices', 'Mont Blanc Triple Épices', 'Brasserie du Mont Blanc', 'France', 'biereDeGarde', 6.5, 'Ambrée maltée aux notes de caramel, d''amande grillée et d''épices.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('mont-blanc-cristal-ipa', 'Cristal IPA', 'Brasserie du Mont Blanc', 'France', 'sessionIpa', 4.7, 'Session IPA chamoniarde, élue meilleure Session IPA au monde aux World Beer Awards 2019.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('meteor-wendelinus', 'Wendelinus', 'Brasserie Meteor', 'France', 'belgianDubbel', 6.8, 'Bière d''abbaye ambrée dans la tradition des moines de Wissembourg.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('meteor-wendelinus-intensia', 'Wendelinus Intensia', 'Brasserie Meteor', 'France', 'quadrupel', 9.0, 'Version plus intense et plus forte de la Wendelinus.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('meteor-blanche', 'Meteor Blanche', 'Brasserie Meteor', 'France', 'witbier', 4.8, 'Blanche alsacienne légère de la plus ancienne brasserie familiale d''Alsace.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('la-cagole-blanche', 'La Cagole Blanche', 'Brasserie La Phocéenne', 'France', 'witbier', 4.7, 'Blanche marseillaise à base de malt d''orge et de froment.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('la-cagole-ipa', 'La Cagole IPA', 'Brasserie La Phocéenne', 'France', 'ipa', 6.0, 'IPA marseillaise relevée d''une pointe de safran récolté au pied des collines de Marseille.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('jenlain-blonde', 'Jenlain Blonde', 'Brasserie Duyck', 'France', 'biereDeGarde', 7.5, 'Bière de garde blonde de la Brasserie Duyck, pendant de la Jenlain Ambrée.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('jenlain-triple', 'Jenlain Triple', 'Brasserie Duyck', 'France', 'belgianTripel', 8.5, 'Blonde non filtrée à triple fermentation, présentée sur lie pour plus de complexité.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ninkasi-french-ipa', 'Ninkasi French IPA', 'Ninkasi', 'France', 'ipa', 5.4, 'IPA brassée avec des houblons et malts 100% français, robe rousse cuivrée.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ninkasi-ambree', 'Ninkasi Ambrée', 'Ninkasi', 'France', 'americanAmberAle', 4.5, 'Ambrée lyonnaise de la brasserie Ninkasi.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ninkasi-blanche', 'Ninkasi Blanche', 'Ninkasi', 'France', 'witbier', 4.8, 'Blanche élaborée avec des malts de froment et d''orge, nez fruité et citronné.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ninkasi-triple', 'Ninkasi Triple', 'Ninkasi', 'France', 'belgianTripel', 8.4, 'Triple lyonnaise de la brasserie Ninkasi, brassée à Tarare.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('bapbap-originale', 'BAPBAP Originale', 'BAPBAP', 'France', 'paleAle', 5.8, 'Pale Ale de fermentation haute, référence de la brasserie parisienne d''Oberkampf.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('bapbap-vertigo', 'Vertigo', 'BAPBAP', 'France', 'ipa', 6.5, 'Première IPA de la brasserie BAPBAP, ambrée et aromatique.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('deck-donohue-pilsner-d', 'Pilsner D', 'Deck & Donohue', 'France', 'pilsner', 5.0, 'Pilsner francilienne de la brasserie Deck & Donohue, fondée à Bonneuil-sur-Marne en 2014.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('deck-donohue-mission-pale-ale', 'Mission Pale Ale', 'Deck & Donohue', 'France', 'paleAle', 4.5, 'Session Pale Ale aux houblons Cascade et Summit, fruitée et peu amère.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('desperados-red', 'Desperados Red', 'Fischer (Heineken)', 'France', 'americanLager', 6.0, 'Desperados aromatisée à la cachaça, aux fruits rouges et au guarana.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('desperados-mojito', 'Desperados Mojito', 'Fischer (Heineken)', 'France', 'americanLager', 5.9, 'Desperados revisitée façon cocktail, notes de menthe et de citron vert.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('gallia-west-ipa', 'Gallia West IPA', 'Gallia', 'France', 'ipa', 6.0, 'West Coast IPA de la brasserie parisienne Gallia, de retour depuis 2009.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('gallia-blonde', 'Gallia Blonde Non Filtrée', 'Gallia', 'France', 'belgianBlonde', 5.8, 'Blonde non filtrée de Gallia, la bière parisienne historique depuis 1890.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('gallia-east-ipa', 'Gallia East IPA', 'Gallia', 'France', 'neipa', 6.0, 'New England IPA de Gallia, trouble et fruitée.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('la-parisienne-blonde', 'La Parisienne Blonde', 'La Parisienne', 'France', 'paleAle', 5.5, 'Pale Ale blonde non filtrée et non pasteurisée, née à Paris en 2014.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('gavroche', 'Gavroche', 'Brasserie de Saint-Sylvestre', 'France', 'biereDeGarde', 8.5, 'Bière de garde ambrée et forte, résultat de plusieurs années de recherche lancée en 1997.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('mont-des-cats-blonde', 'Mont des Cats Blonde', 'Abbaye du Mont des Cats', 'France', 'belgianBlonde', 6.5, 'Blonde dorée et rafraîchissante de la gamme de l''abbaye du Mont des Cats.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('mont-des-cats-brune', 'Mont des Cats Brune', 'Abbaye du Mont des Cats', 'France', 'belgianDubbel', 7.6, 'Brune intense et complexe de la gamme de l''abbaye du Mont des Cats.');
