-- Ajoute les colonnes de logo (Wikimedia Commons, licences libres),
-- utilisées comme repère visuel sur la carte détaillée par pays.
-- Un monogramme (première lettre du nom) sert de repli côté app
-- quand aucun logo fiable n'a été trouvé.
alter table brewery_locations add column if not exists logo_url text;
alter table brewery_locations add column if not exists logo_credit text;

-- 32 logos trouvés automatiquement sur Wikimedia Commons.
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Bitburger_Brauerei_%28Logo%29.jpg/330px-Bitburger_Brauerei_%28Logo%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Bitburger Braugruppe Unternehmenskommunikation (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Bitburger';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/Logo_meteor_quadri_%2Bbaseline.jpg/330px-Logo_meteor_quadri_%2Bbaseline.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Brasserie Meteor (CC BY 3.0), via Wikimedia Commons' where brewery = 'Brasserie Meteor';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Logo_Brasseries_Kronenbourg_2023.png/330px-Logo_Brasseries_Kronenbourg_2023.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Brasseries Kronenbourg (Public domain), via Wikimedia Commons' where brewery = 'Kronenbourg';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/LOGO_PERONI_VUOTO_RBG.png/330px-LOGO_PERONI_VUOTO_RBG.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : AziendaBirraPeroni (Public domain), via Wikimedia Commons' where brewery = 'Peroni';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Carlsberg_logo_at_the_Tetley%27s_brewery%2C_Leeds_%2824th_June_2010%29.jpg/330px-Carlsberg_logo_at_the_Tetley%27s_brewery%2C_Leeds_%2824th_June_2010%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Mtaylor848 (CC BY-SA 3.0), via Wikimedia Commons' where brewery = 'Carlsberg';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Grolsch_Logo.png/330px-Grolsch_Logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Grolsch (Public domain), via Wikimedia Commons' where brewery = 'Grolsch';
update brewery_locations set logo_url = 'https://upload.wikimedia.org/wikipedia/commons/0/00/Efes_Pilsen_logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', logo_credit = 'Logo : Efes pilsen brand itself. (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Efes';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Rothaus-Cube_Logo-2006.jpg/330px-Rothaus-Cube_Logo-2006.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Team Rothaus-Cube (CC BY 2.5), via Wikimedia Commons' where brewery = 'Rothaus';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Lagunitas-logo-2017.png/330px-Lagunitas-logo-2017.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Lagunitas Brewing Company (Public domain), via Wikimedia Commons' where brewery = 'Lagunitas Brewing';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Alaskan_Brewing_Logo_.png/330px-Alaskan_Brewing_Logo_.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Wracealaskan (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Alaskan Brewing';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Anchor_Steam_stained_glass_logo.JPG/330px-Anchor_Steam_stained_glass_logo.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Picardin (CC BY 4.0), via Wikimedia Commons' where brewery = 'Anchor Brewing';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Leffe_Logo.png/330px-Leffe_Logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : AB InBev (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Leffe';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Brasserie_de_Silly_wordmark_logo.png/330px-Brasserie_de_Silly_wordmark_logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Brasserie de Silly (Public domain), via Wikimedia Commons' where brewery = 'Brasserie de Silly';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Gambrinus_logo%28Beer-_czech_republic%29.jpg/330px-Gambrinus_logo%28Beer-_czech_republic%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : cs:User:Pernak (CC BY-SA 3.0), via Wikimedia Commons' where brewery = 'Gambrinus';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Logo_Radeberger_Pilsner_am_Darreturm_der_Radeberger_Exportbierbrauerei.jpg/330px-Logo_Radeberger_Pilsner_am_Darreturm_der_Radeberger_Exportbierbrauerei.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Fiver, der Hellseher (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Radeberger';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Licher_Logo.jpg/330px-Licher_Logo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Licher Privatbrauerei Jhring-Melchior GmbH (Public domain), via Wikimedia Commons' where brewery = 'Licher';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Coors_Brewing_Company_Logo.jpg/330px-Coors_Brewing_Company_Logo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo Public domain, via Wikimedia Commons' where brewery = 'Coors';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Oriental_Brewery_Co.%2CLtd._logo.jpg/330px-Oriental_Brewery_Co.%2CLtd._logo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Oriental Brewery Co.,Ltd. (Public domain), via Wikimedia Commons' where brewery = 'Oriental Brewery';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Baltika_logo_2025.png/330px-Baltika_logo_2025.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : ООО «Пивоваренная компания «Балтика» (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Baltika';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/East_African_Breweries_EABL_2022_Logo.png/330px-East_African_Breweries_EABL_2022_Logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Elvis Otieno (CC0), via Wikimedia Commons' where brewery = 'East African Breweries';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Quilmes_Logo_Nuevo.png/330px-Quilmes_Logo_Nuevo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Cervecería y Maltería Quilmes (Public domain), via Wikimedia Commons' where brewery = 'Quilmes';
update brewery_locations set logo_url = 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Presidente_Beer_Logo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', logo_credit = 'Logo : Cervecería Nacional Dominicana, C. por A. (Public domain), via Wikimedia Commons' where brewery = 'Cervecería Nacional Dominicana';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Logo-apb.png/330px-Logo-apb.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo Public domain, via Wikimedia Commons' where brewery = 'Heineken Asia Pacific';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/Klosterbrauerei_Andechs_logo.png/330px-Klosterbrauerei_Andechs_logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Klosterbrauerei Andechs (Public domain), via Wikimedia Commons' where brewery = 'Kloster Andechs';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Camden_Town_Brewery_Logo.png/330px-Camden_Town_Brewery_Logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Haydjuice (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Camden Town Brewery';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Ur-Krostitzer_-_uk-logo.png/330px-Ur-Krostitzer_-_uk-logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Krostitzer Brauerei GmbH (Public domain), via Wikimedia Commons' where brewery = 'Ur-Krostitzer';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/OB_Type_Logo.png/330px-OB_Type_Logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Terry Kishiyama (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Oskar Blues';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/FWBC_Logo.png/330px-FWBC_Logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Jwilsonfirestone (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Firestone Walker';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Goose_Island_Beer_Co._logo_%2831478241163%29.jpg/330px-Goose_Island_Beer_Co._logo_%2831478241163%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Ruth Hartnup from Vancouver, Canada (CC BY 2.0), via Wikimedia Commons' where brewery = 'Goose Island';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Greene_King_logo_-_geograph.org.uk_-_3482642.jpg/330px-Greene_King_logo_-_geograph.org.uk_-_3482642.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Philip Halling (CC BY-SA 2.0), via Wikimedia Commons' where brewery = 'Greene King';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Orkney_Brewery_logo.png/330px-Orkney_Brewery_logo.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Stephlfulton (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Orkney Brewery';
update brewery_locations set logo_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Logo_Brouwerij_Halve_maan.jpg/330px-Logo_Brouwerij_Halve_maan.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', logo_credit = 'Logo : Franky Schutz (CC BY-SA 4.0), via Wikimedia Commons' where brewery = 'Brouwerij De Halve Maan';
