-- Ajoute des bières françaises supplémentaires (craft régional : Lot,
-- Nord, Bretagne, Corse), à la demande de l'utilisateur ("Ratz etc.").

-- 8 nouvelles brasseries géolocalisées (OpenStreetMap/Nominatim, ODbL).
insert into brewery_locations (brewery, lat, lng, city, address) values ('Brasserie Ratz', 44.310561, 1.4965305, 'Fontanes', 'Brasserie Artisanale Ratz, Fontanes, Cahors, Lot, Occitanie, France');
insert into brewery_locations (brewery, lat, lng, city, address) values ('Brasserie Thiriez', 50.8850479, 2.4329004, 'Esquelbecq', 'Brasserie Thiriez, Rue de Wormhout, Esquelbecq, Dunkerque, Nord, Hauts-de-France, France');
insert into brewery_locations (brewery, lat, lng, city, address) values ('Brasserie La Choulette', 50.2604359, 3.3130002, 'Hordain', 'Brasserie La Choulette, Rue Voltaire, Hordain, Valenciennes, Nord, Hauts-de-France, France');
insert into brewery_locations (brewery, lat, lng, city, address) values ('Brasserie Coreff', 48.2787325, -3.5634342, 'Carhaix-Plouguer', 'Brasserie Coreff, 2 Place Jean Rohou, Carhaix-Plouguer, Finistère, Bretagne, France');
insert into brewery_locations (brewery, lat, lng, city, address) values ('Brasserie Lancelot', 47.8711865, -2.4754713, 'Le Roc-Saint-André', 'Brasserie Lancelot, Le Roc-Saint-André, Val d''Oust, Morbihan, Bretagne, France');
insert into brewery_locations (brewery, lat, lng, city, address) values ('Brasserie Pietra', 42.6584811, 9.4151285, 'Furiani', 'Furiani, Bastia, Haute-Corse, Corse, France');
insert into brewery_locations (brewery, lat, lng, city, address) values ('Brasserie du Pays Flamand', 50.6910154, 2.3978443, 'Blaringhem', 'Brasserie du Pays Flamand, Rue André Plockyn, Blaringhem, Dunkerque, Nord, Hauts-de-France, France');
insert into brewery_locations (brewery, lat, lng, city, address) values ('Brasserie de Bretagne', 47.8591563, -3.8708726, 'Trégunc', 'Brasserie Britt (Brasserie de Bretagne), Trégunc, Quimper, Finistère, Bretagne, France');

-- 24 nouvelles bières françaises.
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ratz-blonde', 'Ratz Blonde', 'Brasserie Ratz', 'France', 'belgianBlonde', 5.0, 'Blonde artisanale non filtrée et non pasteurisée, brassée dans le Lot depuis 2001.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ratz-blanche', 'Ratz Blanche', 'Brasserie Ratz', 'France', 'witbier', 5.0, 'Blanche du Lot, légère et rafraîchissante, primée au Concours Général Agricole.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ratz-ambree', 'Ratz Ambrée', 'Brasserie Ratz', 'France', 'americanAmberAle', 5.0, 'Ambrée artisanale du Quercy aux notes maltées rondes.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ratz-brune', 'Ratz Brune', 'Brasserie Ratz', 'France', 'brownAle', 5.0, 'Brune de tradition, brassée dans le Lot par la première brasserie artisanale de la région.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ratz-triple', 'Ratz Triple', 'Brasserie Ratz', 'France', 'belgianTripel', 7.2, 'Triple généreuse et dorée, primée au Concours Général Agricole 2024.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('ratz-ipa', 'Ratz IPA', 'Brasserie Ratz', 'France', 'ipa', 6.0, 'IPA du Lot, houblonnée et fruitée, non filtrée pour préserver ses arômes.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('biere-du-demon', 'Bière du Démon', 'Brasseurs de Gayant', 'France', 'barleywine', 12.0, 'Blonde forte du Nord lancée il y a plus de trente ans, très maltée avec de belles notes de caramel.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('mega-demon', 'Mega Demon', 'Brasseurs de Gayant', 'France', 'barleywine', 16.0, 'Version ultra forte de la Bière du Démon, l''une des bières les plus alcoolisées du marché français.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('blonde-esquelbecq', 'Blonde d''Esquelbecq', 'Brasserie Thiriez', 'France', 'biereDeGarde', 6.5, 'Bière signature de la brasserie fondée par Daniel Thiriez en 1996, référence du renouveau du craft français.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('etoile-du-nord', 'Étoile du Nord', 'Brasserie Thiriez', 'France', 'saison', 5.5, 'Saison houblonnée généreusement en Goldings, qui a fait la réputation de la brasserie.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('choulette-ambree', 'La Choulette Ambrée', 'Brasserie La Choulette', 'France', 'biereDeGarde', 8.0, 'Bière de garde ambrée aux malts spéciaux, notes de caramel et de pruneau.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('sans-culottes-ambree', 'Bière des Sans Culottes Ambrée', 'Brasserie La Choulette', 'France', 'biereDeGarde', 9.0, 'Bière de caractère du Nord, hommage aux révolutionnaires de 1789 qui libérèrent la bière des taxes.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('coreff-blonde', 'Coreff Blonde', 'Brasserie Coreff', 'France', 'paleAle', 4.5, 'Blonde bretonne qui a marqué la renaissance des microbrasseries françaises dès 1985 à Morlaix.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('coreff-ambree', 'Coreff Ambrée', 'Brasserie Coreff', 'France', 'americanAmberAle', 4.7, 'Ambrée bretonne de la brasserie historique de Carhaix.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('cervoise-lancelot', 'Cervoise Lancelot', 'Brasserie Lancelot', 'France', 'saison', 6.0, 'Bière rousse de tradition gauloise, brassée avec du miel et sept plantes selon une méthode antérieure au houblon.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('telenn-du', 'Telenn Du', 'Brasserie Lancelot', 'France', 'brownAle', 4.5, 'L''une des premières bières au blé noir (sarrasin) d''Europe, brune, légère et délicate.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('pietra', 'Pietra', 'Brasserie Pietra', 'France', 'vienna', 5.5, 'Bière ambrée corse à la farine de châtaigne, la référence de l''île.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('colomba', 'Colomba', 'Brasserie Pietra', 'France', 'witbier', 5.0, 'Blanche corse parfumée aux herbes du maquis : arbousier, myrte, ciste et genièvre.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('serena', 'Serena', 'Brasserie Pietra', 'France', 'euroPaleLager', 5.0, 'Blonde 100% pur malt de la brasserie corse, à l''amertume très fine.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('anosteke-blonde', 'Anosteké Blonde', 'Brasserie du Pays Flamand', 'France', 'belgianStrongGolden', 8.0, 'Blonde forte et élégante du Pays Flamand, plusieurs fois primée.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('anosteke-ipa', 'Anosteké IPA', 'Brasserie du Pays Flamand', 'France', 'ipa', 6.0, 'IPA de la Brasserie du Pays Flamand, dans les Hauts-de-France.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('anosteke-extra-stout', 'Anosteké Extra Stout', 'Brasserie du Pays Flamand', 'France', 'imperialStout', 8.5, 'Stout intense et corsé de la Brasserie du Pays Flamand.');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('dremmwel-blonde-bio', 'Dremmwel Blonde Bio', 'Brasserie de Bretagne', 'France', 'belgianBlonde', 5.0, 'Blonde bio bretonne, ronde et fruitée, brassée à Trégunc (ex-Brasserie Britt).');
insert into beers (id, name, brewery, country, style_id, abv, description) values ('chti-ambree', 'Ch''ti Ambrée', 'Brasserie Castelain', 'France', 'biereDeGarde', 6.2, 'Bière de garde ambrée du Nord, élue parmi les 100 meilleures bières au monde.');
