-- Ajoute la colonne de crédit photo (auteur + licence), nécessaire
-- maintenant que les photos viennent de deux sources différentes
-- (Open Food Facts, Wikimedia Commons) avec des attributions propres.
alter table beers add column if not exists image_credit text;

-- Rétro-attribution des 116 photos déjà en base (source Open Food Facts).
update beers set image_credit = 'Open Food Facts (CC BY-SA)' where image_url ilike '%openfoodfacts%' and image_credit is null;

-- 36 correspondances trouvées automatiquement sur Wikimedia Commons
-- pour des bières restées sans photo après les deux passes Open Food Facts.
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Peroni_Nastro_Azzurro_Beer_Oct_2012.jpg/500px-Peroni_Nastro_Azzurro_Beer_Oct_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'WestportWiki (CC BY-SA 3.0), via Wikimedia Commons' where id = 'peroni-nastro-azzurro';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Kronenbourg_1664_Blanc_at_Hemingway%27s.jpg/500px-Kronenbourg_1664_Blanc_at_Hemingway%27s.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'JIP (CC BY-SA 4.0), via Wikimedia Commons' where id = '1664-blanc';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/94/Efes_Pilsen_beer_on_the_shop_window_Migros.jpg/500px-Efes_Pilsen_beer_on_the_shop_window_Migros.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Ayratayrat (CC BY-SA 4.0), via Wikimedia Commons' where id = 'efes-pilsen';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Hofbr%C3%A4u_M%C3%BCnchen_Hofbr%C3%A4u_Dunkel.JPG/500px-Hofbr%C3%A4u_M%C3%BCnchen_Hofbr%C3%A4u_Dunkel.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Hofbräu München Pressestelle (CC BY-SA 4.0), via Wikimedia Commons' where id = 'hofbrau-dunkel';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Oktoberfest-M%C3%A4rzen_Hacker-Pschorr.jpg/500px-Oktoberfest-M%C3%A4rzen_Hacker-Pschorr.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Boonekamp (CC0), via Wikimedia Commons' where id = 'hacker-pschorr-oktoberfest';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Paulaner_Salvator_Front_and_Back.jpg/500px-Paulaner_Salvator_Front_and_Back.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'SCholewiak (CC BY-SA 2.0), via Wikimedia Commons' where id = 'paulaner-salvator';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Budweiser_Anheuser-Busch.JPG/500px-Budweiser_Anheuser-Busch.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Sergei S. Scurfield (CC BY-SA 3.0), via Wikimedia Commons' where id = 'budweiser';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Bottle_and_glas_of_Chinese_Tsingtao_beer.jpg/500px-Bottle_and_glas_of_Chinese_Tsingtao_beer.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Derbrauni (CC BY-SA 3.0), via Wikimedia Commons' where id = 'tsingtao';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Blue_Aluminum_Bud_Light_Beer_Bottle_Commemorating_the_2009_All-Star_Game_-_DPLA_-_38b6075a9863a6805f3e63d3bc2ea495_%28page_1%29.jpg/500px-Blue_Aluminum_Bud_Light_Beer_Bottle_Commemorating_the_2009_All-Star_Game_-_DPLA_-_38b6075a9863a6805f3e63d3bc2ea495_%28page_1%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Anheuser-Busch Companies, LLC (Public domain), via Wikimedia Commons' where id = 'bud-light';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Sinebrychoff_Porter.jpg/500px-Sinebrychoff_Porter.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Bernt Rostad from Oslo, Norway (CC BY 2.0), via Wikimedia Commons' where id = 'sinebrychoff-porter';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Okocim_Porter.JPG/500px-Okocim_Porter.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'LeeKeoma (Public domain), via Wikimedia Commons' where id = 'okocim-porter';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/LEG_OF_PORK_AND_SCHUMACHER_ALT_BIER_AT_FERD_SCHUMACHER_BIERBRAUEREI_OST_STRASSE_DUSSELDORF_GERMANY_APRIL_2013_%288694989383%29.jpg/500px-LEG_OF_PORK_AND_SCHUMACHER_ALT_BIER_AT_FERD_SCHUMACHER_BIERBRAUEREI_OST_STRASSE_DUSSELDORF_GERMANY_APRIL_2013_%288694989383%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'calflier001 (CC BY-SA 2.0), via Wikimedia Commons' where id = 'schumacher-alt';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Pliny_the_Elder.jpg/500px-Pliny_the_Elder.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Mike McCune (CC BY 2.0), via Wikimedia Commons' where id = 'pliny-the-elder';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Dogfish_Head_90_minute_IPA.JPG/500px-Dogfish_Head_90_minute_IPA.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'HighKing (CC BY-SA 3.0), via Wikimedia Commons' where id = 'dogfish-head-90-minute';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/New_Belgium_Fat_Tire_Amber_Ale_%2815718952987%29.jpg/500px-New_Belgium_Fat_Tire_Amber_Ale_%2815718952987%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Erik Cleves Kristensen (CC BY 2.0), via Wikimedia Commons' where id = 'fat-tire-amber-ale';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Pelforth_brune.jpg/500px-Pelforth_brune.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Dysmorodrepanis (CC BY-SA 3.0), via Wikimedia Commons' where id = 'pelforth-brune';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Rodenbach_grand_cru_bottle.jpg/500px-Rodenbach_grand_cru_bottle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Bertrouf (CC BY-SA 3.0), via Wikimedia Commons' where id = 'rodenbach-grand-cru';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Sierra_Nevada_Bigfoot.jpg/500px-Sierra_Nevada_Bigfoot.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'user:Geographer (CC BY 2.5), via Wikimedia Commons' where id = 'sierra-nevada-bigfoot';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Affligem_Blonde.jpg/500px-Affligem_Blonde.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Miguel Andrade (CC0), via Wikimedia Commons' where id = 'affligem-blonde';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Delirium_tremens_2012_091.JPG/500px-Delirium_tremens_2012_091.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Gordito1869 (CC BY 3.0), via Wikimedia Commons' where id = 'delirium-tremens';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Silly_Saison.jpg/500px-Silly_Saison.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Bernt Rostad from Oslo, Norway (CC BY 2.0), via Wikimedia Commons' where id = 'saison-silly';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1d/Weihenstephaner_Vitus_beer.JPG/500px-Weihenstephaner_Vitus_beer.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'LeeKeoma (CC0), via Wikimedia Commons' where id = 'weihenstephaner-vitus';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/86/Cantillon_Grand_Cru_Bruocsella_%285806231128%29.jpg/500px-Cantillon_Grand_Cru_Bruocsella_%285806231128%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Smabs Sputzer (1956-2017) (CC BY 2.0), via Wikimedia Commons' where id = 'cantillon-grand-cru';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Lindemans_-_Faro_%2B_bottle.png/500px-Lindemans_-_Faro_%2B_bottle.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Strangerhappenings (CC BY-SA 4.0), via Wikimedia Commons' where id = 'lindemans-faro';
update beers set image_url = 'https://upload.wikimedia.org/wikipedia/commons/2/28/Berliner-Weisse-Beer-Glass.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', image_credit = 'BFunken (CC BY-SA 3.0), via Wikimedia Commons' where id = 'berliner-kindl-weisse';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/25/Radeberger_Pilsner.jpg/500px-Radeberger_Pilsner.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Miguel Andrade (CC0), via Wikimedia Commons' where id = 'radeberger-pilsner';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Tuborg_case_of_beer_chilled_in_snow_Aarhus_Denmark.jpg/500px-Tuborg_case_of_beer_chilled_in_snow_Aarhus_Denmark.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Ciara Ní Riain (CC BY-SA 4.0), via Wikimedia Commons' where id = 'tuborg';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/44/Cerveza_Cristal_2.jpg/500px-Cerveza_Cristal_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Jorge Barrios (Public domain), via Wikimedia Commons' where id = 'cristal';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/%D0%91%D0%B0%D0%BB%D1%82%D0%B8%D0%BA%D0%B0_7.JPG/500px-%D0%91%D0%B0%D0%BB%D1%82%D0%B8%D0%BA%D0%B0_7.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Petar Milošević (CC BY-SA 3.0), via Wikimedia Commons' where id = 'baltika-7';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/Tusker_East_African_Breweries.jpg/500px-Tusker_East_African_Breweries.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Thisisjustmynewusername (CC BY-SA 4.0), via Wikimedia Commons' where id = 'tusker';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Bucanero_lata_y_copa.jpg/500px-Bucanero_lata_y_copa.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Yricardopupo (CC BY-SA 4.0), via Wikimedia Commons' where id = 'bucanero';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/Quilmes_Clasica_Lata.jpg/500px-Quilmes_Clasica_Lata.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Flipwared (CC BY-SA 4.0), via Wikimedia Commons' where id = 'quilmes';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Weihenstephaner_Korbinian_beer.JPG/500px-Weihenstephaner_Korbinian_beer.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'LeeKeoma (CC0), via Wikimedia Commons' where id = 'weihenstephaner-korbinian';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Liberty_Ale_%2814511344709%29.jpg/500px-Liberty_Ale_%2814511344709%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Erik Cleves Kristensen (CC BY 2.0), via Wikimedia Commons' where id = 'anchor-liberty-ale';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Beamish_Genuine_Irish_Stout.jpg/500px-Beamish_Genuine_Irish_Stout.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'James Cridland (CC BY 2.0), via Wikimedia Commons' where id = 'beamish-irish-stout';
update beers set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Maredsous_blond_bier.jpg/500px-Maredsous_blond_bier.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', image_credit = 'Queeste (CC BY-SA 3.0), via Wikimedia Commons' where id = 'maredsous-blond';
